// Generated by JavaCPP version 1.5.2: DO NOT EDIT THIS FILE

#include <jni.h>
#include <vulkan/vulkan.hpp>
#include "VKWrap.h"

#ifdef __cplusplus
extern "C" {
#endif
JNIIMPORT int JavaCPP_init(int argc, const char *argv[]);
JNIIMPORT int JavaCPP_uninit();

#ifdef __cplusplus
}
#endif
